In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import svm

boston = datasets.load_boston()
boston.data.shape, boston.target.shape

((506, 13), (506,))

In [5]:
X_train, X_test, y_train, y_test = train_test_split( boston.data, boston.target, test_size = 0.4, random_state = 0)
   

print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

regression = svm.SVR(kernel = 'linear', C = 1).fit(X_train, y_train)
regression.score(X_test, y_test)

(303, 13) (303,)
(203, 13) (203,)


0.6674313821605447

In [7]:
from sklearn.model_selection import cross_val_score
regression = svm.SVR(kernel = 'linear', C=1)
scores = cross_val_score(regression, boston.data, boston.target, cv = 5)
scores


array([0.77279839, 0.72778244, 0.56131595, 0.15056486, 0.082128  ])

In [10]:
print("Accuracy: %0.2f (+/- %0.2f)"%(scores.mean(), scores.std()**2))

Accuracy: 0.46 (+/- 0.08)


In [11]:
import numpy as np
from sklearn.model_selection import KFold

X = ['a', 'b', 'c', 'd']
kf = KFold(n_splits = 2)
for train, test in kf.split(X):
    print('%s %s'%(train, test))

[2 3] [0 1]
[0 1] [2 3]


In [14]:
from sklearn.model_selection import StratifiedKFold

X = np.ones(10)
y = [0,0,0,0,1,1,1,1,1,1]
skf = StratifiedKFold(n_splits = 3)
for train,test in skf.split(X,y):
    print("%s %s"%(train, test))

[2 3 6 7 8 9] [0 1 4 5]
[0 1 3 4 5 8 9] [2 6 7]
[0 1 2 4 5 6 7] [3 8 9]


In [18]:
from sklearn.preprocessing import StandardScaler 
from sklearn.decomposition import PCA
# from sklearn.linear_model import Logistic Regression
from sklearn import svm
from sklearn.pipeline import make_pipeline
#pipe_lr = make_pipeline(StandardScaler(),PCA = (n_components = 2),svm.SVR(kernel = 'linear', C=1))
                        
pipe_svm = make_pipeline(StandardScaler(),
                        PCA(n_components=2),
                        svm.SVR(kernel = 'linear', C=1))
pipe_svm.fit(X_train, y_train)
y_pred = pipe_svm.predict(X_test)
print("Test Accuracy: %0.3f"%pipe_svm.score(X_test, y_test))

Test Accuracy: 0.391


In [21]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(estimator=svm,
                        X=X_train
                        y=y_train,
                        cv=10,
                        n_jobs=1)
print("Cv acuracy score: %s"% scores)

SyntaxError: invalid syntax (<ipython-input-21-fd97f6f944e9>, line 4)